apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shopflow-db
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: shopflow-secretstore
    kind: ClusterSecretStore
  target:
    name: shopflow-db
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: shopflow/db
        property: username
    - secretKey: password
      remoteRef:
        key: shopflow/db
        property: password
    - secretKey: host
      remoteRef:
        key: shopflow/db
        property: host
    - secretKey: dbname
      remoteRef:
        key: shopflow/db
        property: dbname
